### ISSUE TITLE
request.object.existed() always returns true

### ISSUE THREAD

**Issue by flound1129** [ParsePlatform/Parse-SDK-JS#160]
https://developers.facebook.com/bugs/1675561372679121/

**Comment by flound1129** [comment]
verified this is still an issue on 1.6.14

**Comment by andrewimm** [comment]
Turns out this is not an issue with the JS SDK, but with cloud code. A fix has already been found, and is pending review and deployment.

**Comment by andrewimm** [comment]
Fixed.

**Comment by emkman** [comment]
@andrewimm The Parse command line tool allows you to select the version of the JS SDK that runs in the cloud code, so your statement is confusing to me. What version should be set using the `parse jssdk` command to ensure this is fixed?

**Comment by andrewimm** [comment]
This wasn't an SDK issue, but an issue with the internals of the cloud code environment. You don't need to adjust the SDK version to fix this, but we recommend you always use the latest version available.

**Comment by emkman** [comment]
OK that is interesting because I am experiencing an issue currently where existed() is returning false for User objects that are not new. Reverting the SDK to 1.5.0 doesn't fix it, so it makes sense that it is an "internal" issue, but it seems to be broken yet again.

**Comment by andrewimm** [comment]
The issue I referenced only affected SDKs > 1.6, so I doubt what you're seeing is related.

**Comment by emkman** [comment]
I thought the SDK didn't matter? The issue I am experiencing seems to be the same as this: https://developers.facebook.com/bugs/1675561372679121/
which is how I found this GitHub. `existed()` is always returning **false**, even when updating an existing object. I see this is an issue about `existed()` incorrectly returning true. Regardless it's been verified to be broken in my case. I will try upgrading to 1.6.14.

**Comment by emkman** [comment]
Looks like this is the proper issue: https://github.com/ParsePlatform/Parse-SDK-JS/issues/69 It is definitely still broken for me. Can you check your test application you mention?

**Comment by andrewimm** [comment]
Test application reads out fine for me. If you believe you have a reproducible bug, please open a new issue with code that can reliably reproduce the problem, and provide as much information as you can.

**Comment by Psvetly** [comment]
I'm experiencing almost the same as emkman.
Parse JavaScript SDK Version: 1.6.14.
The same is for me in beforeSave. isNew() always returns true
```
Parse.Cloud.beforeSave("RMEvent", function(request, response) {
    Parse.Cloud.useMasterKey();
if (!request.object.isNew())
{
    response.success();
}
else
{
    response.error("Event already exists");
}
}
```
And existed() always returns false:
```
Parse.Cloud.beforeSave("RMEvent", function(request, response) {
    Parse.Cloud.useMasterKey();
if (request.object.existed())
{
    response.success();
}
else
{
    response.error("Event already exists");
}
}
```

**Comment by andrewimm** [comment]
@Psvetly `isNew` is working as intended -- per the documentation, it returns true if "the object has never been saved to Parse." Under the hood, it just returns true in the absence of the object id.
`existed()` should work, though. I'll take another look at the tests we set up the last time this happened, but unless there was some rollback of our server software, it should be fine.

**Comment by andrewimm** [comment]
Just ran the tests with an object that existed; `existed()` returned true.

**Comment by emkman** [comment]
@andrewimm It is possible that my issue is specific to Parse.User. Please see the new issue I created per your request: https://github.com/ParsePlatform/Parse-SDK-JS/issues/196#issuecomment-179749235
